import { TrainerCardModel } from "@/models/trainerCard.model";
export const dummyTrainers: TrainerCardModel[] = [
    {
        name: "sanya_gupta",
        full_name: "Sanya Gupta",
        avg_rating: 4.5,
        expertise_in: "yoga, cricket",
        city: "Pune",
        language: "English",
        charge: 1800,
        profile_views: 0,
        status: "active",
        image: "/assets/prof-1.jpeg",
        is_wishlisted: 0,
    },
    {
        name: "rahul_vedfrma",
        full_name: "Rahul Verma",
        avg_rating: 4.0,
        expertise_in: "yoga, cricket",
        city: "Delhi",
        language: "English",
        charge: 2500,
        profile_views: 0,
        status: "active",
        image: "/assets/trainer1.jpg",
        is_wishlisted: 0,
    },
    {
        name: "anjalisd_mehta",
        full_name: "Anjali Mehta",
        avg_rating: 5.0,
        expertise_in: "yoga, cricket",
        city: "Mumbai",
        language: "English",
        charge: 2200,
        profile_views: 0,
        status: "active",
        image: "/assets/trainer2.jpg",
        is_wishlisted: 0,
    },
    {
        name: "sddfkiran_rao",
        full_name: "Kiran Rao",
        avg_rating: 4.0,
        expertise_in: "yoga, cricket",
        city: "Bengaluru",
        language: "English",
        charge: 1800,
        profile_views: 0,
        status: "active",
        image: "/assets/trainer3.jpg",
        is_wishlisted: 0,
    },
    {
        name: "sanyfdsa_gupta",
        full_name: "Sanya Gupta",
        avg_rating: 4.5,
        expertise_in: "yoga, cricket",
        city: "Pune",
        language: "English",
        charge: 1800,
        profile_views: 0,
        status: "active",
        image: "/assets/trainer4.jpg",
        is_wishlisted: 0,
    },
    {
        name: "rasahul_verma",
        full_name: "Rahul Verma",
        avg_rating: 4.0,
        expertise_in: "yoga, cricket",
        city: "Delhi",
        language: "English",
        charge: 2500,
        profile_views: 0,
        status: "active",
        image: "/rahul.jpg",
        is_wishlisted: 1,
    },
    {
        name: "agffnjali_mehta",
        full_name: "Anjali Mehta",
        avg_rating: 5.0,
        expertise_in: "yoga, cricket",
        city: "Mumbai",
        language: "English",
        charge: 2200,
        profile_views: 0,
        status: "active",
        image: "/anjali.jpg",
        is_wishlisted: 0,
    },
    {
        name: "kiran_asdrao",
        full_name: "Kiran Rao",
        avg_rating: 4.0,
        expertise_in: "yoga, cricket",
        city: "Bengaluru",
        language: "English",
        charge: 1800,
        profile_views: 0,
        status: "active",
        image: "/kiran.jpg",
        is_wishlisted: 1,
    },


]