
export const expertise_in: string[] = [
    "Leadership",
    "Negotiation",
    "POSH",
    "Sales",
    "Executive Presence",
    "Coaching",
    "Customer Service",
    "Wellbeing",
    "Conflict",
    "Decision Making",
    "Creativity",
    "Innovation",
    "Change",
    "Inclusion",
    "Strategy",
    "Productivity",
    "Finance",
    "Mindfulness",
    "Resilience",
    "Custom",
    "Fitness",
    "Public Speaking",
    "LGBTQIA+",
    "Marketing",
    "AI",
    "Communication",
    "Life Coach",
    "Team Building",
    "Learning & Development",
    "Diversity & Inclusion",
    "Public Speaker",
    "Interview Specialist",
    "Resume Writing",
    "Time Management",
    "Personality Development",
    "Career Coach"
 
]