// List of major Indian cities
export const indianCities = [
    "Adoni", "Agartala", "Ahmedabad", "Ahmednagar", "Aizawl", "Ajmer", "Akola", "Aligarh", "Alwar", "Ambernath",
    "Amravati", "Amritsar", "Anand", "Anantapur", "Anantnag", "Arrah", "Asansol", "Aurangabad", "Avadi", "Bahraich",
    "Bally", "Bengaluru", "Baranagar", "Barasat", "Bareilly", "Barrackpore", "Bathinda", "Begusarai", "Belgaum",
    "Bellary", "Berhampore", "Berhampur", "Betiah", "Bhadrak", "Bhadravati", "Bhagalpur", "Bharatpur", "Bhatpara",
    "Bhavnagar", "Bhilai", "Bhilwara", "Bhind", "Bhiwandi", "Bhiwani", "Bhopal", "Bhubaneswar", "Bhuj", "Bidar",
    "Bidhan Nagar", "Bijapur", "Bilaspur", "Bokaro", "Burhanpur", "Chandannagar", "Chandigarh", "Chandrapur",
    "Chapra", "Chennai", "Chittoor", "Coimbatore", "Cuttack", "Darbhanga", "Davanagere", "Dehradun", "Dehri",
    "Delhi", "Dewas", "Dhanbad", "Dindigul", "Durg", "Durgapur", "Eluru", "Etawah", "Faizabad", "Faridabad",
    "Farrukhabad", "Fatehpur", "Firozabad", "Gandhidham", "Gandhinagar", "Gaya", "Ghaziabad", "Gopalpur", "Gulbarga",
    "Guna", "Guntur", "Gurgaon", "Guwahati", "Gwalior", "Hajipur", "Haldia", "Haldwani", "Hapur", "Haridwar",
    "Hisar", "Hospet", "Hugli-Chinsurah", "Hyderabad", "Ichalkaranji", "Imphal", "Indore", "Jabalpur", "Jaipur",
    "Jalandhar", "Jalgaon", "Jalna", "Jammu", "Jamnagar", "Jamshedpur", "Jhansi", "Jodhpur", "Junagadh", "Kadapa",
    "Kakinada", "Kalyan", "Kamarhati", "Kamptee", "Kanpur", "Karawal Nagar", "Karimnagar", "Karnal", "Katihar",
    "Khora", "Kochi", "Kolhapur", "Kolkata", "Kollam", "Korba", "Kota", "Kozhikode", "Kulti", "Kurnool", "Latur",
    "Loni", "Lucknow", "Ludhiana", "Machilipatnam", "Madanapalle", "Madurai", "Mahesana", "Maheshtala", "Malegaon",
    "Mangalore", "Mathura", "Medininagar", "Meerut", "Mirzapur", "Mormugao", "Moradabad", "Morena", "Munger",
    "Mumbai", "Muzaffarnagar", "Muzaffarpur", "Mysore", "Nadiad", "Nagercoil", "Nagpur", "Naihati", "Nanded",
    "Nandyal", "Nashik", "Navi Mumbai", "New Delhi", "Nizamabad", "Noida", "North Barrackpur", "North Dumdum",
    "Ongole", "Orai", "Ozhukarai", "Panihati", "Panipat", "Panchkula", "Parbhani", "Pali", "Pallavaram", "Patiala",
    "Patna", "Phagwara", "Phusro", "Puducherry", "Pune", "Purnia", "Raebareli", "Raichur", "Raipur", "Rajkot",
    "Rajpur Sonarpur", "Ramagundam", "Rampur", "Ratlam", "Rewa", "Rohtak", "Rourkela", "Rourkela Industrial Township",
    "Sagar", "Saharanpur", "Saharsa", "Salem", "Sambalpur", "Sambhal", "Sangli-Miraj", "Satara", "Satna", "Secunderabad",
    "Shahjahanpur", "Shivamogga", "Shivpuri", "Sikar", "Silchar", "Siliguri", "Singrauli", "Siwan", "Solapur",
    "Sonipat", "South Dumdum", "Sri Ganganagar", "Surat", "Surendranagar", "Thane", "Thanjavur", "Thrissur",
    "Thoothukudi", "Tirunelveli", "Tirupur", "Tiruvottiyur", "Titagarh", "Tumkur", "Udaipur", "Ujjain", "Ulhasnagar",
    "Uluberia", "Unnao", "Vadodara", "Varanasi", "Vasco Da Gama", "Vendhar Nagar", "Vellore", "Vijayanagaram",
    "Vijayawada", "Visakhapatnam", "Warangal", "Yamunanagar"
];