import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from '@/context/UserContext';
import { ThemeProvider } from "@/styles/ThemeProvider";
import { ThemeToggle } from "@/components/ThemeToggle";
import { LoadingProvider } from '@/context/LoadingContext';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <UserProvider>
          <ThemeProvider>
            <ThemeToggle />
            <LoadingProvider>
              {children}
            </LoadingProvider>
          </ThemeProvider>
        </UserProvider>

      </body>
    </html>
  );
}
